### ISSUE TITLE
Docker multistage build and quesitons

### ISSUE THREAD

**Issue by AndreaGiardini** [livetocode/camunda-prometheus-exporter#1]
Hello

Interesting project that you started, thank you! :)

I would be glad to help with this exporter. The first thing that comes to my mind is the Dockerfile structure. I got a multistage Dockerfile working but I am asking myself if you had a particular reason for keeping them separate (building/publish)...

In general, it would be nice if you could file some issues in order to better understand what is left to implement and organize our efforts.

Keep me updated

**Comment by livetocode** [comment]
Hi,
Thanks for your interest!
It's still very alpha and customized for our own needs, but any help would be appreciated for sure!
Especially since I'm not a Go Expert nor a Camunda one ;-)
I separated the scripts, just to be able to build and run locally without publishing.
I saw that we can also use the new docker features for multistage builds (https://docs.docker.com/engine/userguide/eng-image/multistage-build/#name-your-build-stages) but it requires a very recent docker version...
